ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.Category = "VislRP"
ENT.BaseHealth = 10
ENT.Cost = 100
ENT.Limit = 3
ENT.Owner = nil
ENT.PrintName = "Ammo Dispenser"
ENT.Author = "Dexter"
ENT.Purpose = "Give Ammo"
ENT.Instructions = "Place and Use"
ENT.Spawnable = false
ENT.AdminSpawnable = true
ENT.Model = "models/Items/ammocrate_smg1.mdl"